#!/bin/bash
top="$(dirname "$0")/.."

if [ -z "$1" ]
then
  config="$top/etc/riemann.config"
else
  config=$1
fi

exec java -XX:+UseConcMarkSweepGC -jar "$top/lib/riemann-0.1.2-standalone.jar" "$config"
